// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
Texture2D<float2> inputTexture;
RWStructuredBuffer<float2> dataBuffer;
uint width;


[numthreads(32,32,1)]
void CSMain (uint3 id : SV_DispatchThreadID) 
{
    dataBuffer[id.x + id.y * width] = inputTexture[id.xy].xy;
}
