namespace Gameplay.Productions
{
    public enum EProduct
    {
        COAL_ORE,
        IRON_ORE,
        COPPER_ORE,
        GOLD_ORE,
        SILVER_ORE,
        IRON_INGOT,
        COPPER_INGOT,
        GOLD_INGOT,
        SILVER_INGOT,
        IRON_PLATES,
        CIRCUIT_BOARD,
        COMPUTER,
        OIL,
        PLASTIC,
        RUBBER,
        CABLE,
        TIRES,
        ENGINE,
        CARBODY,
        CAR,
    }

    public enum EProduction
    {
        COAL_MINE,
        IRON_MINE,
        COPPER_MINE,
        GOLD_MINE,
        SILVER_MINE,
        IRON_MELTER,
        COPPER_MELTER,
        GOLD_MELTER,
        SILVER_MELTER,
        IRON_PRESS,
        MICRO_ELECTRONICS_MANUFACTURER,
        ELECTRONICS_MANUFACTURER,
        OIL_PUMP,
        PLASTIC_MANUFACTURE,
        RUBBER_MANUFACTURE,
        CABLE_MANUFACTURE,
        TIRES_MANUFACTURE,
        ENGINE_MANUFACTURE,
        CARBODY_MANUFACTURE,
        CAR_MANUFACTURE,
    }
}
